# Generated by Django 2.2.4 on 2019-08-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCLiquorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('ml', models.DecimalField(decimal_places=2, max_digits=15)),
                ('upc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('refnumber', models.CharField(max_length=100)),
                ('customernumber', models.IntegerField()),
                ('customerPST', models.CharField(max_length=100)),
                ('customername', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiptreader.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bcliquoritem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiptreader.BCLiquorItem')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiptreader.Output')),
            ],
        ),
    ]
