# Generated by Django 2.2.6 on 2019-11-09 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receiptreader', '0002_processedreceipt_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='raw_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receiptreader.RawReceipt'),
        ),
    ]
