# Generated by Django 2.2.4 on 2019-10-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptreader', '0003_auto_20191002_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bcliquoritemprice',
            name='item',
        ),
        migrations.RemoveField(
            model_name='line',
            name='bcliquoritem',
        ),
        migrations.RemoveField(
            model_name='line',
            name='output',
        ),
        migrations.RemoveField(
            model_name='output',
            name='document',
        ),
        migrations.RemoveField(
            model_name='rawjson',
            name='file',
        ),
        migrations.RemoveField(
            model_name='rawjson',
            name='name',
        ),
        migrations.AddField(
            model_name='rawjson',
            name='text',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BCLiquorItem',
        ),
        migrations.DeleteModel(
            name='BCLiquorItemPrice',
        ),
        migrations.DeleteModel(
            name='Line',
        ),
        migrations.DeleteModel(
            name='Output',
        ),
    ]
