# Generated by Django 2.2.6 on 2019-10-17 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receiptreader', '0004_auto_20191003_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(verbose_name='SKU')),
                ('description', models.CharField(max_length=100, verbose_name='Item Name')),
                ('unit_price', models.FloatField(blank=True, null=True, verbose_name='Unit Price')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('line_total', models.FloatField(blank=True, null=True, verbose_name='Unit Sub Total')),
                ('container_deposit', models.FloatField()),
                ('tax_code', models.CharField(choices=[('G', 'G'), ('L', 'L')], max_length=2)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiptreader.Receipt')),
            ],
        ),
        migrations.CreateModel(
            name='BillTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_pst', models.CharField(blank=True, max_length=50, null=True, verbose_name='PST')),
                ('custom_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Number')),
                ('custom_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('custom_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('custom_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('custom_prov', models.CharField(blank=True, max_length=5, null=True, verbose_name='Prov')),
                ('custom_postal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiptreader.Receipt')),
            ],
        ),
        migrations.CreateModel(
            name='BillFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiptreader.Receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Postal')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date Time')),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True, verbose_name='Card Last 4 Number')),
                ('card_type', models.CharField(blank=True, choices=[('VI', 'VI'), ('MC', 'MC'), ('DP', 'DP')], max_length=2, null=True, verbose_name='Card Type')),
                ('grand_total', models.FloatField(blank=True, null=True, verbose_name='Grand Total')),
                ('total_deposit', models.FloatField(blank=True, null=True, verbose_name='Total Deposit')),
                ('total_gst', models.FloatField(blank=True, null=True, verbose_name='Total GST')),
                ('total_pst', models.FloatField(blank=True, null=True, verbose_name='Total PST')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiptreader.Receipt')),
            ],
        ),
    ]
