# Generated by Django 2.2.6 on 2019-10-17 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receiptreader', '0006_auto_20191017_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receiptreader.Receipt'),
        ),
    ]
