# Generated by Django 2.2.6 on 2019-10-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiptreader', '0008_auto_20191017_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='container_deposit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='tax_code',
            field=models.CharField(blank=True, choices=[('G', 'G'), ('L', 'L')], max_length=2, null=True),
        ),
    ]
