# Generated by Django 2.2.6 on 2019-10-23 09:04

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province/State')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hierarchy', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
